### ISSUE TITLE
Error: Cannot find module 'mineflayer'

### ISSUE THREAD

**Issue by anny414** [urFate/Afk-Bot#11]
Receiving following error 
```
Error: Cannot find module 'mineflayer'
Require stack:
- /home/runner/Afk-Bot/bot.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/Afk-Bot/bot.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/Afk-Bot/bot.js' ]
}
exit status 1

```
I am trying this Bot on repl it Please add a button for Heroku

**Comment by urFate** [comment]
> Receiving following error
> 
> ```
> Error: Cannot find module 'mineflayer'
> Require stack:
> - /home/runner/Afk-Bot/bot.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
>     at Module.require (internal/modules/cjs/loader.js:887:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/home/runner/Afk-Bot/bot.js:1:20)
>     at Module._compile (internal/modules/cjs/loader.js:999:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>     at Module.load (internal/modules/cjs/loader.js:863:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/home/runner/Afk-Bot/bot.js' ]
> }
> exit status 1
> 
> ```
> 
> I am trying this Bot on repl it Please add a button for Heroku

Did you run `npm install` command?
