### ISSUE TITLE
Invalid Username Or password

### ISSUE THREAD

**Issue by Ragemalik** [urFate/Afk-Bot#25]
Hello!

So when i try run it i get

Error: Invalid credentials. Invalid username or password.
    at call (/root/Afk-Bot/node_modules/yggdrasil/src/utils.js:35:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async auth (/root/Afk-Bot/node_modules/yggdrasil/src/Client.js:18:12)
[ERROR] Invalid credentials. Invalid username or password.

My settings.json looks like this

{
  "bot-account": {
    "username": "email@outlook.com",
    "password": "password",
    "type": "Microsoft"
  },

The credentials are defiantly correct

**Comment by urFate** [comment]
I was updated Mineflayer lib in last commit. It's probably fix your problem.

**Comment by NoMercyJustFire** [comment]
I've had the same problem, is there a fix?  Changing the mineflyer lib didnt help either
