### ISSUE TITLE
Getting some code issues while running after like 3-5 mins

### ISSUE THREAD

**Issue by lachyharris** [urFate/Afk-Bot#6]
Hey, having some error codes hitting me, wondering if you can read and tell me whats going on with it? Error code attached below

    at checkStatus (C:\Users\harri\afk_bot\node_modules\minecraft-protocol\src\client\microsoftAuth.js:125:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.authenticatePassword (C:\Users\harri\afk_bot\node_modules\minecraft-protocol\src\client\microsoftAuth.js:81:34)
[ERROR] Too Many Requests

does this few times until it basically gives up

**Comment by lachyharris** [comment]
Also got this error just now:

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
[ERROR] read ECONNRESET

**Comment by lachyharris** [comment]
Could be coincidental but seem to be in water both times errors have hit\

**Comment by urFate** [comment]
I think its [minecraft-protocol](https://github.com/PrismarineJS/node-minecraft-protocol) or [mineflayer](https://github.com/PrismarineJS/mineflayer/) issue. Afk-Bot just uses this libs and don't working with servers on low level. 
I recommend reopen this issue on the repositories listed above.
