### ISSUE TITLE
Unsupported protocol version: 1.19.3

### ISSUE THREAD

**Issue by kristupas098** [urFate/Afk-Bot#60]
Afk-Bot-1.3.0/node_modules/minecraft-protocol/src/createClient.js:28
  if (!mcData) throw new Error(`unsupported protocol version: ${optVersion}`)
               ^

Error: unsupported protocol version: 1.19.3
    at Object.createClient (/home/krist/Desktop/share/yeetus/Afk-Bot-1.3.0/node_modules/minecraft-protocol/src/createClient.js:28:22)
    at Object.createBot (/home/krist/Desktop/share/yeetus/Afk-Bot-1.3.0/node_modules/mineflayer/lib/loader.js:96:35)
    at createBot (/home/krist/Desktop/share/yeetus/Afk-Bot-1.3.0/bot.js:12:27)
    at Object.<anonymous> (/home/krist/Desktop/share/yeetus/Afk-Bot-1.3.0/bot.js:170:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.13.0

Downloaded latest version form releases and latest node js version

**Comment by JohnKearney1** [comment]
bump ^ same issue

**Comment by urFate** [comment]
Fixed in #[2cd58d1](https://github.com/urFate/Afk-Bot/commit/2cd58d1dd42eb44813b364a662f79a2c778c507d)
